# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Optical Flow' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Optical Flow

pod 'OpenCV', '~> 3.4.2.0'

end
